"""phase7_recruitment_onboarding

Revision ID: 41c84cf629d5
Revises: a3968f076537
Create Date: 2026-08-16 07:55:26.003148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c84cf629d5'
down_revision: Union[str, Sequence[str], None] = 'a3968f076537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_tasks_category'), 'onboarding_tasks', ['category'], unique=False)
    op.add_column('departments', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('departments', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'description')
    op.drop_column('departments', 'code')
    op.drop_index(op.f('ix_onboarding_tasks_category'), table_name='onboarding_tasks')
    op.drop_table('onboarding_tasks')
    # ### end Alembic commands ###
