"""phase5_godown_warehouse_operations

Revision ID: a3968f076537
Revises: 0164f3bf329d
Create Date: 2026-08-15 17:09:48.899111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3968f076537'
down_revision: Union[str, Sequence[str], None] = '0164f3bf329d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('godown_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('godown_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_godown_alerts_godown_id'), 'godown_alerts', ['godown_id'], unique=False)
    op.create_index(op.f('ix_godown_alerts_product_id'), 'godown_alerts', ['product_id'], unique=False)
    op.create_table('godown_user_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('godown_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'godown_id', name='uq_godown_user')
    )
    op.create_index(op.f('ix_godown_user_assignments_godown_id'), 'godown_user_assignments', ['godown_id'], unique=False)
    op.create_index(op.f('ix_godown_user_assignments_user_id'), 'godown_user_assignments', ['user_id'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('reserved_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_reservations_order_id'), 'inventory_reservations', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_product_id'), 'inventory_reservations', ['product_id'], unique=False)
    op.create_table('packing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('packed_by_id', sa.UUID(), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('total_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('packed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_records_order_id'), 'packing_records', ['order_id'], unique=True)
    op.create_table('product_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('godown_id', sa.UUID(), nullable=False),
    sa.Column('rack', sa.String(length=50), nullable=True),
    sa.Column('shelf', sa.String(length=50), nullable=True),
    sa.Column('bin', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'godown_id', name='uq_product_godown_location')
    )
    op.create_index(op.f('ix_product_locations_godown_id'), 'product_locations', ['godown_id'], unique=False)
    op.create_index(op.f('ix_product_locations_product_id'), 'product_locations', ['product_id'], unique=False)
    op.create_table('picking_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('required_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('picked_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('picked_by_id', sa.UUID(), nullable=True),
    sa.Column('picked_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['picked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picking_records_order_id'), 'picking_records', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_picking_records_order_id'), table_name='picking_records')
    op.drop_table('picking_records')
    op.drop_index(op.f('ix_product_locations_product_id'), table_name='product_locations')
    op.drop_index(op.f('ix_product_locations_godown_id'), table_name='product_locations')
    op.drop_table('product_locations')
    op.drop_index(op.f('ix_packing_records_order_id'), table_name='packing_records')
    op.drop_table('packing_records')
    op.drop_index(op.f('ix_inventory_reservations_product_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_order_id'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index(op.f('ix_godown_user_assignments_user_id'), table_name='godown_user_assignments')
    op.drop_index(op.f('ix_godown_user_assignments_godown_id'), table_name='godown_user_assignments')
    op.drop_table('godown_user_assignments')
    op.drop_index(op.f('ix_godown_alerts_product_id'), table_name='godown_alerts')
    op.drop_index(op.f('ix_godown_alerts_godown_id'), table_name='godown_alerts')
    op.drop_table('godown_alerts')
    # ### end Alembic commands ###
