/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as HomeRouteImport } from './routes/home'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PortalSelectRouteImport } from './routes/portal-select'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as BusinessAiRouteImport } from './routes/business/ai'
import { Route as BusinessAnalyticsRouteImport } from './routes/business/analytics'
import { Route as BusinessCartRouteImport } from './routes/business/cart'
import { Route as BusinessCatalogRouteImport } from './routes/business/catalog'
import { Route as BusinessCheckoutRouteImport } from './routes/business/checkout'
import { Route as BusinessDashboardRouteImport } from './routes/business/dashboard'
import { Route as BusinessInvoicesRouteImport } from './routes/business/invoices'
import { Route as BusinessPaymentsRouteImport } from './routes/business/payments'
import { Route as BusinessProfileRouteImport } from './routes/business/profile'
import { Route as BusinessQuotesRouteImport } from './routes/business/quotes'
import { Route as BusinessRecurringRouteImport } from './routes/business/recurring'
import { Route as BusinessRegisterRouteImport } from './routes/business/register'
import { Route as BusinessSettingsRouteImport } from './routes/business/settings'
import { Route as BusinessSupportRouteImport } from './routes/business/support'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as DriverIndexRouteImport } from './routes/driver/index'
import { Route as DriverAiRouteImport } from './routes/driver/ai'
import { Route as DriverDashboardRouteImport } from './routes/driver/dashboard'
import { Route as DriverHistoryRouteImport } from './routes/driver/history'
import { Route as DriverNavigationRouteImport } from './routes/driver/navigation'
import { Route as DriverNotificationsRouteImport } from './routes/driver/notifications'
import { Route as DriverProfileRouteImport } from './routes/driver/profile'
import { Route as DriverSupportRouteImport } from './routes/driver/support'
import { Route as FarmerIndexRouteImport } from './routes/farmer/index'
import { Route as FarmerAiRouteImport } from './routes/farmer/ai'
import { Route as FarmerDashboardRouteImport } from './routes/farmer/dashboard'
import { Route as FarmerEarningsRouteImport } from './routes/farmer/earnings'
import { Route as FarmerInventoryRouteImport } from './routes/farmer/inventory'
import { Route as FarmerNotificationsRouteImport } from './routes/farmer/notifications'
import { Route as FarmerPaymentsRouteImport } from './routes/farmer/payments'
import { Route as FarmerPickupsRouteImport } from './routes/farmer/pickups'
import { Route as FarmerProfileRouteImport } from './routes/farmer/profile'
import { Route as FarmerRegisterRouteImport } from './routes/farmer/register'
import { Route as FarmerSettingsRouteImport } from './routes/farmer/settings'
import { Route as FarmerSupportRouteImport } from './routes/farmer/support'
import { Route as GodownIndexRouteImport } from './routes/godown/index'
import { Route as GodownAiRouteImport } from './routes/godown/ai'
import { Route as GodownAlertsRouteImport } from './routes/godown/alerts'
import { Route as GodownAllocationRouteImport } from './routes/godown/allocation'
import { Route as GodownBatchesRouteImport } from './routes/godown/batches'
import { Route as GodownColdStorageRouteImport } from './routes/godown/cold-storage'
import { Route as GodownDashboardRouteImport } from './routes/godown/dashboard'
import { Route as GodownEmployeesRouteImport } from './routes/godown/employees'
import { Route as GodownExpiryRouteImport } from './routes/godown/expiry'
import { Route as GodownInboundRouteImport } from './routes/godown/inbound'
import { Route as GodownInventoryRouteImport } from './routes/godown/inventory'
import { Route as GodownLocationsRouteImport } from './routes/godown/locations'
import { Route as GodownOutboundRouteImport } from './routes/godown/outbound'
import { Route as GodownReportsRouteImport } from './routes/godown/reports'
import { Route as GodownSettingsRouteImport } from './routes/godown/settings'
import { Route as GodownTasksRouteImport } from './routes/godown/tasks'
import { Route as OfficeComplianceRouteImport } from './routes/office/compliance'
import { Route as OfficeDashboardRouteImport } from './routes/office/dashboard'
import { Route as OfficeReconciliationRouteImport } from './routes/office/reconciliation'
import { Route as OfficeReportsRouteImport } from './routes/office/reports'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as RecruitmentIndexRouteImport } from './routes/recruitment/index'
import { Route as RecruitmentAiRouteImport } from './routes/recruitment/ai'
import { Route as RecruitmentAnalyticsRouteImport } from './routes/recruitment/analytics'
import { Route as RecruitmentDashboardRouteImport } from './routes/recruitment/dashboard'
import { Route as RecruitmentDirectoryRouteImport } from './routes/recruitment/directory'
import { Route as RecruitmentOnboardingRouteImport } from './routes/recruitment/onboarding'
import { Route as RecruitmentSettingsRouteImport } from './routes/recruitment/settings'
import { Route as TransportIndexRouteImport } from './routes/transport/index'
import { Route as TransportAiRouteImport } from './routes/transport/ai'
import { Route as TransportAssignmentsRouteImport } from './routes/transport/assignments'
import { Route as TransportBulkLogisticsRouteImport } from './routes/transport/bulk-logistics'
import { Route as TransportDashboardRouteImport } from './routes/transport/dashboard'
import { Route as TransportHistoryRouteImport } from './routes/transport/history'
import { Route as TransportHomeDeliveryRouteImport } from './routes/transport/home-delivery'
import { Route as TransportMaintenanceRouteImport } from './routes/transport/maintenance'
import { Route as TransportMoreRouteImport } from './routes/transport/more'
import { Route as TransportQueueRouteImport } from './routes/transport/queue'
import { Route as TransportShiftsRouteImport } from './routes/transport/shifts'
import { Route as TransportTrackingRouteImport } from './routes/transport/tracking'
import { Route as BusinessOrdersIndexRouteImport } from './routes/business/orders/index'
import { Route as BusinessOrdersOrderIdRouteImport } from './routes/business/orders/$orderId'
import { Route as BusinessProductsProductIdRouteImport } from './routes/business/products/$productId'
import { Route as DriverDeliveriesIndexRouteImport } from './routes/driver/deliveries/index'
import { Route as DriverDeliveriesOrderIdRouteImport } from './routes/driver/deliveries/$orderId'
import { Route as DriverDeliveriesPickupVerificationRouteImport } from './routes/driver/deliveries/pickup-verification'
import { Route as DriverDeliveriesProofOfDeliveryRouteImport } from './routes/driver/deliveries/proof-of-delivery'
import { Route as DriverDeliveriesReportProblemRouteImport } from './routes/driver/deliveries/report-problem'
import { Route as DriverDeliveriesSuccessRouteImport } from './routes/driver/deliveries/success'
import { Route as DriverVehicleIndexRouteImport } from './routes/driver/vehicle/index'
import { Route as FarmerOrdersIndexRouteImport } from './routes/farmer/orders/index'
import { Route as FarmerOrdersOrderIdRouteImport } from './routes/farmer/orders/$orderId'
import { Route as FarmerProductsIndexRouteImport } from './routes/farmer/products/index'
import { Route as FarmerProductsAddRouteImport } from './routes/farmer/products/add'
import { Route as GodownProductsIndexRouteImport } from './routes/godown/products/index'
import { Route as GodownProductsProductIdRouteImport } from './routes/godown/products/$productId'
import { Route as GodownProductsHistoryRouteImport } from './routes/godown/products/history'
import { Route as GodownProductsNewRouteImport } from './routes/godown/products/new'
import { Route as RecruitmentAccountsIndexRouteImport } from './routes/recruitment/accounts/index'
import { Route as RecruitmentApplicationsIndexRouteImport } from './routes/recruitment/applications/index'
import { Route as RecruitmentApplicationsDetailsRouteImport } from './routes/recruitment/applications/details'
import { Route as RecruitmentVerificationIndexRouteImport } from './routes/recruitment/verification/index'
import { Route as TransportAlertsIndexRouteImport } from './routes/transport/alerts/index'
import { Route as TransportDriversIndexRouteImport } from './routes/transport/drivers/index'
import { Route as TransportEmployeesIndexRouteImport } from './routes/transport/employees/index'
import { Route as TransportReportsIndexRouteImport } from './routes/transport/reports/index'
import { Route as TransportRoutesIndexRouteImport } from './routes/transport/routes/index'
import { Route as TransportVehiclesIndexRouteImport } from './routes/transport/vehicles/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSelectRoute = PortalSelectRouteImport.update({
  id: '/portal-select',
  path: '/portal-select',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAiRoute = BusinessAiRouteImport.update({
  id: '/business/ai',
  path: '/business/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAnalyticsRoute = BusinessAnalyticsRouteImport.update({
  id: '/business/analytics',
  path: '/business/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCartRoute = BusinessCartRouteImport.update({
  id: '/business/cart',
  path: '/business/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCatalogRoute = BusinessCatalogRouteImport.update({
  id: '/business/catalog',
  path: '/business/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCheckoutRoute = BusinessCheckoutRouteImport.update({
  id: '/business/checkout',
  path: '/business/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDashboardRoute = BusinessDashboardRouteImport.update({
  id: '/business/dashboard',
  path: '/business/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessInvoicesRoute = BusinessInvoicesRouteImport.update({
  id: '/business/invoices',
  path: '/business/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPaymentsRoute = BusinessPaymentsRouteImport.update({
  id: '/business/payments',
  path: '/business/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessProfileRoute = BusinessProfileRouteImport.update({
  id: '/business/profile',
  path: '/business/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessQuotesRoute = BusinessQuotesRouteImport.update({
  id: '/business/quotes',
  path: '/business/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRecurringRoute = BusinessRecurringRouteImport.update({
  id: '/business/recurring',
  path: '/business/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegisterRoute = BusinessRegisterRouteImport.update({
  id: '/business/register',
  path: '/business/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSettingsRoute = BusinessSettingsRouteImport.update({
  id: '/business/settings',
  path: '/business/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSupportRoute = BusinessSupportRouteImport.update({
  id: '/business/support',
  path: '/business/support',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverAiRoute = DriverAiRouteImport.update({
  id: '/driver/ai',
  path: '/driver/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/driver/dashboard',
  path: '/driver/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverHistoryRoute = DriverHistoryRouteImport.update({
  id: '/driver/history',
  path: '/driver/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverNavigationRoute = DriverNavigationRouteImport.update({
  id: '/driver/navigation',
  path: '/driver/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverNotificationsRoute = DriverNotificationsRouteImport.update({
  id: '/driver/notifications',
  path: '/driver/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/driver/profile',
  path: '/driver/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSupportRoute = DriverSupportRouteImport.update({
  id: '/driver/support',
  path: '/driver/support',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/farmer/',
  path: '/farmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerAiRoute = FarmerAiRouteImport.update({
  id: '/farmer/ai',
  path: '/farmer/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/farmer/dashboard',
  path: '/farmer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerEarningsRoute = FarmerEarningsRouteImport.update({
  id: '/farmer/earnings',
  path: '/farmer/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerInventoryRoute = FarmerInventoryRouteImport.update({
  id: '/farmer/inventory',
  path: '/farmer/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerNotificationsRoute = FarmerNotificationsRouteImport.update({
  id: '/farmer/notifications',
  path: '/farmer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerPaymentsRoute = FarmerPaymentsRouteImport.update({
  id: '/farmer/payments',
  path: '/farmer/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerPickupsRoute = FarmerPickupsRouteImport.update({
  id: '/farmer/pickups',
  path: '/farmer/pickups',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerProfileRoute = FarmerProfileRouteImport.update({
  id: '/farmer/profile',
  path: '/farmer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRegisterRoute = FarmerRegisterRouteImport.update({
  id: '/farmer/register',
  path: '/farmer/register',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerSettingsRoute = FarmerSettingsRouteImport.update({
  id: '/farmer/settings',
  path: '/farmer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerSupportRoute = FarmerSupportRouteImport.update({
  id: '/farmer/support',
  path: '/farmer/support',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownIndexRoute = GodownIndexRouteImport.update({
  id: '/godown/',
  path: '/godown/',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownAiRoute = GodownAiRouteImport.update({
  id: '/godown/ai',
  path: '/godown/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownAlertsRoute = GodownAlertsRouteImport.update({
  id: '/godown/alerts',
  path: '/godown/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownAllocationRoute = GodownAllocationRouteImport.update({
  id: '/godown/allocation',
  path: '/godown/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownBatchesRoute = GodownBatchesRouteImport.update({
  id: '/godown/batches',
  path: '/godown/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownColdStorageRoute = GodownColdStorageRouteImport.update({
  id: '/godown/cold-storage',
  path: '/godown/cold-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownDashboardRoute = GodownDashboardRouteImport.update({
  id: '/godown/dashboard',
  path: '/godown/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownEmployeesRoute = GodownEmployeesRouteImport.update({
  id: '/godown/employees',
  path: '/godown/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownExpiryRoute = GodownExpiryRouteImport.update({
  id: '/godown/expiry',
  path: '/godown/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownInboundRoute = GodownInboundRouteImport.update({
  id: '/godown/inbound',
  path: '/godown/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownInventoryRoute = GodownInventoryRouteImport.update({
  id: '/godown/inventory',
  path: '/godown/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownLocationsRoute = GodownLocationsRouteImport.update({
  id: '/godown/locations',
  path: '/godown/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownOutboundRoute = GodownOutboundRouteImport.update({
  id: '/godown/outbound',
  path: '/godown/outbound',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownReportsRoute = GodownReportsRouteImport.update({
  id: '/godown/reports',
  path: '/godown/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownSettingsRoute = GodownSettingsRouteImport.update({
  id: '/godown/settings',
  path: '/godown/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownTasksRoute = GodownTasksRouteImport.update({
  id: '/godown/tasks',
  path: '/godown/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeComplianceRoute = OfficeComplianceRouteImport.update({
  id: '/office/compliance',
  path: '/office/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeDashboardRoute = OfficeDashboardRouteImport.update({
  id: '/office/dashboard',
  path: '/office/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeReconciliationRoute = OfficeReconciliationRouteImport.update({
  id: '/office/reconciliation',
  path: '/office/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeReportsRoute = OfficeReportsRouteImport.update({
  id: '/office/reports',
  path: '/office/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentIndexRoute = RecruitmentIndexRouteImport.update({
  id: '/recruitment/',
  path: '/recruitment/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentAiRoute = RecruitmentAiRouteImport.update({
  id: '/recruitment/ai',
  path: '/recruitment/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentAnalyticsRoute = RecruitmentAnalyticsRouteImport.update({
  id: '/recruitment/analytics',
  path: '/recruitment/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentDashboardRoute = RecruitmentDashboardRouteImport.update({
  id: '/recruitment/dashboard',
  path: '/recruitment/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentDirectoryRoute = RecruitmentDirectoryRouteImport.update({
  id: '/recruitment/directory',
  path: '/recruitment/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentOnboardingRoute = RecruitmentOnboardingRouteImport.update({
  id: '/recruitment/onboarding',
  path: '/recruitment/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentSettingsRoute = RecruitmentSettingsRouteImport.update({
  id: '/recruitment/settings',
  path: '/recruitment/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportIndexRoute = TransportIndexRouteImport.update({
  id: '/transport/',
  path: '/transport/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportAiRoute = TransportAiRouteImport.update({
  id: '/transport/ai',
  path: '/transport/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportAssignmentsRoute = TransportAssignmentsRouteImport.update({
  id: '/transport/assignments',
  path: '/transport/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportBulkLogisticsRoute = TransportBulkLogisticsRouteImport.update({
  id: '/transport/bulk-logistics',
  path: '/transport/bulk-logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportDashboardRoute = TransportDashboardRouteImport.update({
  id: '/transport/dashboard',
  path: '/transport/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportHistoryRoute = TransportHistoryRouteImport.update({
  id: '/transport/history',
  path: '/transport/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportHomeDeliveryRoute = TransportHomeDeliveryRouteImport.update({
  id: '/transport/home-delivery',
  path: '/transport/home-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportMaintenanceRoute = TransportMaintenanceRouteImport.update({
  id: '/transport/maintenance',
  path: '/transport/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportMoreRoute = TransportMoreRouteImport.update({
  id: '/transport/more',
  path: '/transport/more',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportQueueRoute = TransportQueueRouteImport.update({
  id: '/transport/queue',
  path: '/transport/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportShiftsRoute = TransportShiftsRouteImport.update({
  id: '/transport/shifts',
  path: '/transport/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportTrackingRoute = TransportTrackingRouteImport.update({
  id: '/transport/tracking',
  path: '/transport/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOrdersIndexRoute = BusinessOrdersIndexRouteImport.update({
  id: '/business/orders/',
  path: '/business/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOrdersOrderIdRoute = BusinessOrdersOrderIdRouteImport.update({
  id: '/business/orders/$orderId',
  path: '/business/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessProductsProductIdRoute =
  BusinessProductsProductIdRouteImport.update({
    id: '/business/products/$productId',
    path: '/business/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DriverDeliveriesIndexRoute = DriverDeliveriesIndexRouteImport.update({
  id: '/driver/deliveries/',
  path: '/driver/deliveries/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDeliveriesOrderIdRoute = DriverDeliveriesOrderIdRouteImport.update({
  id: '/driver/deliveries/$orderId',
  path: '/driver/deliveries/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDeliveriesPickupVerificationRoute =
  DriverDeliveriesPickupVerificationRouteImport.update({
    id: '/driver/deliveries/pickup-verification',
    path: '/driver/deliveries/pickup-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const DriverDeliveriesProofOfDeliveryRoute =
  DriverDeliveriesProofOfDeliveryRouteImport.update({
    id: '/driver/deliveries/proof-of-delivery',
    path: '/driver/deliveries/proof-of-delivery',
    getParentRoute: () => rootRouteImport,
  } as any)
const DriverDeliveriesReportProblemRoute =
  DriverDeliveriesReportProblemRouteImport.update({
    id: '/driver/deliveries/report-problem',
    path: '/driver/deliveries/report-problem',
    getParentRoute: () => rootRouteImport,
  } as any)
const DriverDeliveriesSuccessRoute = DriverDeliveriesSuccessRouteImport.update({
  id: '/driver/deliveries/success',
  path: '/driver/deliveries/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverVehicleIndexRoute = DriverVehicleIndexRouteImport.update({
  id: '/driver/vehicle/',
  path: '/driver/vehicle/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerOrdersIndexRoute = FarmerOrdersIndexRouteImport.update({
  id: '/farmer/orders/',
  path: '/farmer/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerOrdersOrderIdRoute = FarmerOrdersOrderIdRouteImport.update({
  id: '/farmer/orders/$orderId',
  path: '/farmer/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerProductsIndexRoute = FarmerProductsIndexRouteImport.update({
  id: '/farmer/products/',
  path: '/farmer/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerProductsAddRoute = FarmerProductsAddRouteImport.update({
  id: '/farmer/products/add',
  path: '/farmer/products/add',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownProductsIndexRoute = GodownProductsIndexRouteImport.update({
  id: '/godown/products/',
  path: '/godown/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownProductsProductIdRoute = GodownProductsProductIdRouteImport.update({
  id: '/godown/products/$productId',
  path: '/godown/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownProductsHistoryRoute = GodownProductsHistoryRouteImport.update({
  id: '/godown/products/history',
  path: '/godown/products/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GodownProductsNewRoute = GodownProductsNewRouteImport.update({
  id: '/godown/products/new',
  path: '/godown/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentAccountsIndexRoute =
  RecruitmentAccountsIndexRouteImport.update({
    id: '/recruitment/accounts/',
    path: '/recruitment/accounts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecruitmentApplicationsIndexRoute =
  RecruitmentApplicationsIndexRouteImport.update({
    id: '/recruitment/applications/',
    path: '/recruitment/applications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecruitmentApplicationsDetailsRoute =
  RecruitmentApplicationsDetailsRouteImport.update({
    id: '/recruitment/applications/details',
    path: '/recruitment/applications/details',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecruitmentVerificationIndexRoute =
  RecruitmentVerificationIndexRouteImport.update({
    id: '/recruitment/verification/',
    path: '/recruitment/verification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransportAlertsIndexRoute = TransportAlertsIndexRouteImport.update({
  id: '/transport/alerts/',
  path: '/transport/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportDriversIndexRoute = TransportDriversIndexRouteImport.update({
  id: '/transport/drivers/',
  path: '/transport/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportEmployeesIndexRoute = TransportEmployeesIndexRouteImport.update({
  id: '/transport/employees/',
  path: '/transport/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportReportsIndexRoute = TransportReportsIndexRouteImport.update({
  id: '/transport/reports/',
  path: '/transport/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoutesIndexRoute = TransportRoutesIndexRouteImport.update({
  id: '/transport/routes/',
  path: '/transport/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportVehiclesIndexRoute = TransportVehiclesIndexRouteImport.update({
  id: '/transport/vehicles/',
  path: '/transport/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/portal-select': typeof PortalSelectRoute
  '/business/ai': typeof BusinessAiRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/cart': typeof BusinessCartRoute
  '/business/catalog': typeof BusinessCatalogRoute
  '/business/checkout': typeof BusinessCheckoutRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/business/invoices': typeof BusinessInvoicesRoute
  '/business/payments': typeof BusinessPaymentsRoute
  '/business/profile': typeof BusinessProfileRoute
  '/business/quotes': typeof BusinessQuotesRoute
  '/business/recurring': typeof BusinessRecurringRoute
  '/business/register': typeof BusinessRegisterRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/support': typeof BusinessSupportRoute
  '/driver/ai': typeof DriverAiRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/support': typeof DriverSupportRoute
  '/farmer/ai': typeof FarmerAiRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/earnings': typeof FarmerEarningsRoute
  '/farmer/inventory': typeof FarmerInventoryRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/pickups': typeof FarmerPickupsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/register': typeof FarmerRegisterRoute
  '/farmer/settings': typeof FarmerSettingsRoute
  '/farmer/support': typeof FarmerSupportRoute
  '/godown/ai': typeof GodownAiRoute
  '/godown/alerts': typeof GodownAlertsRoute
  '/godown/allocation': typeof GodownAllocationRoute
  '/godown/batches': typeof GodownBatchesRoute
  '/godown/cold-storage': typeof GodownColdStorageRoute
  '/godown/dashboard': typeof GodownDashboardRoute
  '/godown/employees': typeof GodownEmployeesRoute
  '/godown/expiry': typeof GodownExpiryRoute
  '/godown/inbound': typeof GodownInboundRoute
  '/godown/inventory': typeof GodownInventoryRoute
  '/godown/locations': typeof GodownLocationsRoute
  '/godown/outbound': typeof GodownOutboundRoute
  '/godown/reports': typeof GodownReportsRoute
  '/godown/settings': typeof GodownSettingsRoute
  '/godown/tasks': typeof GodownTasksRoute
  '/office/compliance': typeof OfficeComplianceRoute
  '/office/dashboard': typeof OfficeDashboardRoute
  '/office/reconciliation': typeof OfficeReconciliationRoute
  '/office/reports': typeof OfficeReportsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/recruitment/ai': typeof RecruitmentAiRoute
  '/recruitment/analytics': typeof RecruitmentAnalyticsRoute
  '/recruitment/dashboard': typeof RecruitmentDashboardRoute
  '/recruitment/directory': typeof RecruitmentDirectoryRoute
  '/recruitment/onboarding': typeof RecruitmentOnboardingRoute
  '/recruitment/settings': typeof RecruitmentSettingsRoute
  '/transport/ai': typeof TransportAiRoute
  '/transport/assignments': typeof TransportAssignmentsRoute
  '/transport/bulk-logistics': typeof TransportBulkLogisticsRoute
  '/transport/dashboard': typeof TransportDashboardRoute
  '/transport/history': typeof TransportHistoryRoute
  '/transport/home-delivery': typeof TransportHomeDeliveryRoute
  '/transport/maintenance': typeof TransportMaintenanceRoute
  '/transport/more': typeof TransportMoreRoute
  '/transport/queue': typeof TransportQueueRoute
  '/transport/shifts': typeof TransportShiftsRoute
  '/transport/tracking': typeof TransportTrackingRoute
  '/business/': typeof BusinessIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/godown/': typeof GodownIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/recruitment/': typeof RecruitmentIndexRoute
  '/transport/': typeof TransportIndexRoute
  '/business/orders/$orderId': typeof BusinessOrdersOrderIdRoute
  '/business/products/$productId': typeof BusinessProductsProductIdRoute
  '/driver/deliveries/$orderId': typeof DriverDeliveriesOrderIdRoute
  '/driver/deliveries/pickup-verification': typeof DriverDeliveriesPickupVerificationRoute
  '/driver/deliveries/proof-of-delivery': typeof DriverDeliveriesProofOfDeliveryRoute
  '/driver/deliveries/report-problem': typeof DriverDeliveriesReportProblemRoute
  '/driver/deliveries/success': typeof DriverDeliveriesSuccessRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRoute
  '/farmer/products/add': typeof FarmerProductsAddRoute
  '/godown/products/$productId': typeof GodownProductsProductIdRoute
  '/godown/products/history': typeof GodownProductsHistoryRoute
  '/godown/products/new': typeof GodownProductsNewRoute
  '/recruitment/applications/details': typeof RecruitmentApplicationsDetailsRoute
  '/business/orders/': typeof BusinessOrdersIndexRoute
  '/driver/deliveries/': typeof DriverDeliveriesIndexRoute
  '/driver/vehicle/': typeof DriverVehicleIndexRoute
  '/farmer/orders/': typeof FarmerOrdersIndexRoute
  '/farmer/products/': typeof FarmerProductsIndexRoute
  '/godown/products/': typeof GodownProductsIndexRoute
  '/recruitment/accounts/': typeof RecruitmentAccountsIndexRoute
  '/recruitment/applications/': typeof RecruitmentApplicationsIndexRoute
  '/recruitment/verification/': typeof RecruitmentVerificationIndexRoute
  '/transport/alerts/': typeof TransportAlertsIndexRoute
  '/transport/drivers/': typeof TransportDriversIndexRoute
  '/transport/employees/': typeof TransportEmployeesIndexRoute
  '/transport/reports/': typeof TransportReportsIndexRoute
  '/transport/routes/': typeof TransportRoutesIndexRoute
  '/transport/vehicles/': typeof TransportVehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/portal-select': typeof PortalSelectRoute
  '/business/ai': typeof BusinessAiRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/cart': typeof BusinessCartRoute
  '/business/catalog': typeof BusinessCatalogRoute
  '/business/checkout': typeof BusinessCheckoutRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/business/invoices': typeof BusinessInvoicesRoute
  '/business/payments': typeof BusinessPaymentsRoute
  '/business/profile': typeof BusinessProfileRoute
  '/business/quotes': typeof BusinessQuotesRoute
  '/business/recurring': typeof BusinessRecurringRoute
  '/business/register': typeof BusinessRegisterRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/support': typeof BusinessSupportRoute
  '/driver/ai': typeof DriverAiRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/support': typeof DriverSupportRoute
  '/farmer/ai': typeof FarmerAiRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/earnings': typeof FarmerEarningsRoute
  '/farmer/inventory': typeof FarmerInventoryRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/pickups': typeof FarmerPickupsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/register': typeof FarmerRegisterRoute
  '/farmer/settings': typeof FarmerSettingsRoute
  '/farmer/support': typeof FarmerSupportRoute
  '/godown/ai': typeof GodownAiRoute
  '/godown/alerts': typeof GodownAlertsRoute
  '/godown/allocation': typeof GodownAllocationRoute
  '/godown/batches': typeof GodownBatchesRoute
  '/godown/cold-storage': typeof GodownColdStorageRoute
  '/godown/dashboard': typeof GodownDashboardRoute
  '/godown/employees': typeof GodownEmployeesRoute
  '/godown/expiry': typeof GodownExpiryRoute
  '/godown/inbound': typeof GodownInboundRoute
  '/godown/inventory': typeof GodownInventoryRoute
  '/godown/locations': typeof GodownLocationsRoute
  '/godown/outbound': typeof GodownOutboundRoute
  '/godown/reports': typeof GodownReportsRoute
  '/godown/settings': typeof GodownSettingsRoute
  '/godown/tasks': typeof GodownTasksRoute
  '/office/compliance': typeof OfficeComplianceRoute
  '/office/dashboard': typeof OfficeDashboardRoute
  '/office/reconciliation': typeof OfficeReconciliationRoute
  '/office/reports': typeof OfficeReportsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/recruitment/ai': typeof RecruitmentAiRoute
  '/recruitment/analytics': typeof RecruitmentAnalyticsRoute
  '/recruitment/dashboard': typeof RecruitmentDashboardRoute
  '/recruitment/directory': typeof RecruitmentDirectoryRoute
  '/recruitment/onboarding': typeof RecruitmentOnboardingRoute
  '/recruitment/settings': typeof RecruitmentSettingsRoute
  '/transport/ai': typeof TransportAiRoute
  '/transport/assignments': typeof TransportAssignmentsRoute
  '/transport/bulk-logistics': typeof TransportBulkLogisticsRoute
  '/transport/dashboard': typeof TransportDashboardRoute
  '/transport/history': typeof TransportHistoryRoute
  '/transport/home-delivery': typeof TransportHomeDeliveryRoute
  '/transport/maintenance': typeof TransportMaintenanceRoute
  '/transport/more': typeof TransportMoreRoute
  '/transport/queue': typeof TransportQueueRoute
  '/transport/shifts': typeof TransportShiftsRoute
  '/transport/tracking': typeof TransportTrackingRoute
  '/business': typeof BusinessIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/driver': typeof DriverIndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/godown': typeof GodownIndexRoute
  '/products': typeof ProductsIndexRoute
  '/recruitment': typeof RecruitmentIndexRoute
  '/transport': typeof TransportIndexRoute
  '/business/orders/$orderId': typeof BusinessOrdersOrderIdRoute
  '/business/products/$productId': typeof BusinessProductsProductIdRoute
  '/driver/deliveries/$orderId': typeof DriverDeliveriesOrderIdRoute
  '/driver/deliveries/pickup-verification': typeof DriverDeliveriesPickupVerificationRoute
  '/driver/deliveries/proof-of-delivery': typeof DriverDeliveriesProofOfDeliveryRoute
  '/driver/deliveries/report-problem': typeof DriverDeliveriesReportProblemRoute
  '/driver/deliveries/success': typeof DriverDeliveriesSuccessRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRoute
  '/farmer/products/add': typeof FarmerProductsAddRoute
  '/godown/products/$productId': typeof GodownProductsProductIdRoute
  '/godown/products/history': typeof GodownProductsHistoryRoute
  '/godown/products/new': typeof GodownProductsNewRoute
  '/recruitment/applications/details': typeof RecruitmentApplicationsDetailsRoute
  '/business/orders': typeof BusinessOrdersIndexRoute
  '/driver/deliveries': typeof DriverDeliveriesIndexRoute
  '/driver/vehicle': typeof DriverVehicleIndexRoute
  '/farmer/orders': typeof FarmerOrdersIndexRoute
  '/farmer/products': typeof FarmerProductsIndexRoute
  '/godown/products': typeof GodownProductsIndexRoute
  '/recruitment/accounts': typeof RecruitmentAccountsIndexRoute
  '/recruitment/applications': typeof RecruitmentApplicationsIndexRoute
  '/recruitment/verification': typeof RecruitmentVerificationIndexRoute
  '/transport/alerts': typeof TransportAlertsIndexRoute
  '/transport/drivers': typeof TransportDriversIndexRoute
  '/transport/employees': typeof TransportEmployeesIndexRoute
  '/transport/reports': typeof TransportReportsIndexRoute
  '/transport/routes': typeof TransportRoutesIndexRoute
  '/transport/vehicles': typeof TransportVehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/portal-select': typeof PortalSelectRoute
  '/business/ai': typeof BusinessAiRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/cart': typeof BusinessCartRoute
  '/business/catalog': typeof BusinessCatalogRoute
  '/business/checkout': typeof BusinessCheckoutRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/business/invoices': typeof BusinessInvoicesRoute
  '/business/payments': typeof BusinessPaymentsRoute
  '/business/profile': typeof BusinessProfileRoute
  '/business/quotes': typeof BusinessQuotesRoute
  '/business/recurring': typeof BusinessRecurringRoute
  '/business/register': typeof BusinessRegisterRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/support': typeof BusinessSupportRoute
  '/driver/ai': typeof DriverAiRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/support': typeof DriverSupportRoute
  '/farmer/ai': typeof FarmerAiRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/earnings': typeof FarmerEarningsRoute
  '/farmer/inventory': typeof FarmerInventoryRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/pickups': typeof FarmerPickupsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/register': typeof FarmerRegisterRoute
  '/farmer/settings': typeof FarmerSettingsRoute
  '/farmer/support': typeof FarmerSupportRoute
  '/godown/ai': typeof GodownAiRoute
  '/godown/alerts': typeof GodownAlertsRoute
  '/godown/allocation': typeof GodownAllocationRoute
  '/godown/batches': typeof GodownBatchesRoute
  '/godown/cold-storage': typeof GodownColdStorageRoute
  '/godown/dashboard': typeof GodownDashboardRoute
  '/godown/employees': typeof GodownEmployeesRoute
  '/godown/expiry': typeof GodownExpiryRoute
  '/godown/inbound': typeof GodownInboundRoute
  '/godown/inventory': typeof GodownInventoryRoute
  '/godown/locations': typeof GodownLocationsRoute
  '/godown/outbound': typeof GodownOutboundRoute
  '/godown/reports': typeof GodownReportsRoute
  '/godown/settings': typeof GodownSettingsRoute
  '/godown/tasks': typeof GodownTasksRoute
  '/office/compliance': typeof OfficeComplianceRoute
  '/office/dashboard': typeof OfficeDashboardRoute
  '/office/reconciliation': typeof OfficeReconciliationRoute
  '/office/reports': typeof OfficeReportsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/recruitment/ai': typeof RecruitmentAiRoute
  '/recruitment/analytics': typeof RecruitmentAnalyticsRoute
  '/recruitment/dashboard': typeof RecruitmentDashboardRoute
  '/recruitment/directory': typeof RecruitmentDirectoryRoute
  '/recruitment/onboarding': typeof RecruitmentOnboardingRoute
  '/recruitment/settings': typeof RecruitmentSettingsRoute
  '/transport/ai': typeof TransportAiRoute
  '/transport/assignments': typeof TransportAssignmentsRoute
  '/transport/bulk-logistics': typeof TransportBulkLogisticsRoute
  '/transport/dashboard': typeof TransportDashboardRoute
  '/transport/history': typeof TransportHistoryRoute
  '/transport/home-delivery': typeof TransportHomeDeliveryRoute
  '/transport/maintenance': typeof TransportMaintenanceRoute
  '/transport/more': typeof TransportMoreRoute
  '/transport/queue': typeof TransportQueueRoute
  '/transport/shifts': typeof TransportShiftsRoute
  '/transport/tracking': typeof TransportTrackingRoute
  '/business/': typeof BusinessIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/godown/': typeof GodownIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/recruitment/': typeof RecruitmentIndexRoute
  '/transport/': typeof TransportIndexRoute
  '/business/orders/$orderId': typeof BusinessOrdersOrderIdRoute
  '/business/products/$productId': typeof BusinessProductsProductIdRoute
  '/driver/deliveries/$orderId': typeof DriverDeliveriesOrderIdRoute
  '/driver/deliveries/pickup-verification': typeof DriverDeliveriesPickupVerificationRoute
  '/driver/deliveries/proof-of-delivery': typeof DriverDeliveriesProofOfDeliveryRoute
  '/driver/deliveries/report-problem': typeof DriverDeliveriesReportProblemRoute
  '/driver/deliveries/success': typeof DriverDeliveriesSuccessRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRoute
  '/farmer/products/add': typeof FarmerProductsAddRoute
  '/godown/products/$productId': typeof GodownProductsProductIdRoute
  '/godown/products/history': typeof GodownProductsHistoryRoute
  '/godown/products/new': typeof GodownProductsNewRoute
  '/recruitment/applications/details': typeof RecruitmentApplicationsDetailsRoute
  '/business/orders/': typeof BusinessOrdersIndexRoute
  '/driver/deliveries/': typeof DriverDeliveriesIndexRoute
  '/driver/vehicle/': typeof DriverVehicleIndexRoute
  '/farmer/orders/': typeof FarmerOrdersIndexRoute
  '/farmer/products/': typeof FarmerProductsIndexRoute
  '/godown/products/': typeof GodownProductsIndexRoute
  '/recruitment/accounts/': typeof RecruitmentAccountsIndexRoute
  '/recruitment/applications/': typeof RecruitmentApplicationsIndexRoute
  '/recruitment/verification/': typeof RecruitmentVerificationIndexRoute
  '/transport/alerts/': typeof TransportAlertsIndexRoute
  '/transport/drivers/': typeof TransportDriversIndexRoute
  '/transport/employees/': typeof TransportEmployeesIndexRoute
  '/transport/reports/': typeof TransportReportsIndexRoute
  '/transport/routes/': typeof TransportRoutesIndexRoute
  '/transport/vehicles/': typeof TransportVehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/home'
    | '/onboarding'
    | '/orders'
    | '/portal-select'
    | '/business/ai'
    | '/business/analytics'
    | '/business/cart'
    | '/business/catalog'
    | '/business/checkout'
    | '/business/dashboard'
    | '/business/invoices'
    | '/business/payments'
    | '/business/profile'
    | '/business/quotes'
    | '/business/recurring'
    | '/business/register'
    | '/business/settings'
    | '/business/support'
    | '/driver/ai'
    | '/driver/dashboard'
    | '/driver/history'
    | '/driver/navigation'
    | '/driver/notifications'
    | '/driver/profile'
    | '/driver/support'
    | '/farmer/ai'
    | '/farmer/dashboard'
    | '/farmer/earnings'
    | '/farmer/inventory'
    | '/farmer/notifications'
    | '/farmer/payments'
    | '/farmer/pickups'
    | '/farmer/profile'
    | '/farmer/register'
    | '/farmer/settings'
    | '/farmer/support'
    | '/godown/ai'
    | '/godown/alerts'
    | '/godown/allocation'
    | '/godown/batches'
    | '/godown/cold-storage'
    | '/godown/dashboard'
    | '/godown/employees'
    | '/godown/expiry'
    | '/godown/inbound'
    | '/godown/inventory'
    | '/godown/locations'
    | '/godown/outbound'
    | '/godown/reports'
    | '/godown/settings'
    | '/godown/tasks'
    | '/office/compliance'
    | '/office/dashboard'
    | '/office/reconciliation'
    | '/office/reports'
    | '/products/$productId'
    | '/recruitment/ai'
    | '/recruitment/analytics'
    | '/recruitment/dashboard'
    | '/recruitment/directory'
    | '/recruitment/onboarding'
    | '/recruitment/settings'
    | '/transport/ai'
    | '/transport/assignments'
    | '/transport/bulk-logistics'
    | '/transport/dashboard'
    | '/transport/history'
    | '/transport/home-delivery'
    | '/transport/maintenance'
    | '/transport/more'
    | '/transport/queue'
    | '/transport/shifts'
    | '/transport/tracking'
    | '/business/'
    | '/categories/'
    | '/checkout/'
    | '/driver/'
    | '/farmer/'
    | '/godown/'
    | '/products/'
    | '/recruitment/'
    | '/transport/'
    | '/business/orders/$orderId'
    | '/business/products/$productId'
    | '/driver/deliveries/$orderId'
    | '/driver/deliveries/pickup-verification'
    | '/driver/deliveries/proof-of-delivery'
    | '/driver/deliveries/report-problem'
    | '/driver/deliveries/success'
    | '/farmer/orders/$orderId'
    | '/farmer/products/add'
    | '/godown/products/$productId'
    | '/godown/products/history'
    | '/godown/products/new'
    | '/recruitment/applications/details'
    | '/business/orders/'
    | '/driver/deliveries/'
    | '/driver/vehicle/'
    | '/farmer/orders/'
    | '/farmer/products/'
    | '/godown/products/'
    | '/recruitment/accounts/'
    | '/recruitment/applications/'
    | '/recruitment/verification/'
    | '/transport/alerts/'
    | '/transport/drivers/'
    | '/transport/employees/'
    | '/transport/reports/'
    | '/transport/routes/'
    | '/transport/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/home'
    | '/onboarding'
    | '/orders'
    | '/portal-select'
    | '/business/ai'
    | '/business/analytics'
    | '/business/cart'
    | '/business/catalog'
    | '/business/checkout'
    | '/business/dashboard'
    | '/business/invoices'
    | '/business/payments'
    | '/business/profile'
    | '/business/quotes'
    | '/business/recurring'
    | '/business/register'
    | '/business/settings'
    | '/business/support'
    | '/driver/ai'
    | '/driver/dashboard'
    | '/driver/history'
    | '/driver/navigation'
    | '/driver/notifications'
    | '/driver/profile'
    | '/driver/support'
    | '/farmer/ai'
    | '/farmer/dashboard'
    | '/farmer/earnings'
    | '/farmer/inventory'
    | '/farmer/notifications'
    | '/farmer/payments'
    | '/farmer/pickups'
    | '/farmer/profile'
    | '/farmer/register'
    | '/farmer/settings'
    | '/farmer/support'
    | '/godown/ai'
    | '/godown/alerts'
    | '/godown/allocation'
    | '/godown/batches'
    | '/godown/cold-storage'
    | '/godown/dashboard'
    | '/godown/employees'
    | '/godown/expiry'
    | '/godown/inbound'
    | '/godown/inventory'
    | '/godown/locations'
    | '/godown/outbound'
    | '/godown/reports'
    | '/godown/settings'
    | '/godown/tasks'
    | '/office/compliance'
    | '/office/dashboard'
    | '/office/reconciliation'
    | '/office/reports'
    | '/products/$productId'
    | '/recruitment/ai'
    | '/recruitment/analytics'
    | '/recruitment/dashboard'
    | '/recruitment/directory'
    | '/recruitment/onboarding'
    | '/recruitment/settings'
    | '/transport/ai'
    | '/transport/assignments'
    | '/transport/bulk-logistics'
    | '/transport/dashboard'
    | '/transport/history'
    | '/transport/home-delivery'
    | '/transport/maintenance'
    | '/transport/more'
    | '/transport/queue'
    | '/transport/shifts'
    | '/transport/tracking'
    | '/business'
    | '/categories'
    | '/checkout'
    | '/driver'
    | '/farmer'
    | '/godown'
    | '/products'
    | '/recruitment'
    | '/transport'
    | '/business/orders/$orderId'
    | '/business/products/$productId'
    | '/driver/deliveries/$orderId'
    | '/driver/deliveries/pickup-verification'
    | '/driver/deliveries/proof-of-delivery'
    | '/driver/deliveries/report-problem'
    | '/driver/deliveries/success'
    | '/farmer/orders/$orderId'
    | '/farmer/products/add'
    | '/godown/products/$productId'
    | '/godown/products/history'
    | '/godown/products/new'
    | '/recruitment/applications/details'
    | '/business/orders'
    | '/driver/deliveries'
    | '/driver/vehicle'
    | '/farmer/orders'
    | '/farmer/products'
    | '/godown/products'
    | '/recruitment/accounts'
    | '/recruitment/applications'
    | '/recruitment/verification'
    | '/transport/alerts'
    | '/transport/drivers'
    | '/transport/employees'
    | '/transport/reports'
    | '/transport/routes'
    | '/transport/vehicles'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/home'
    | '/onboarding'
    | '/orders'
    | '/portal-select'
    | '/business/ai'
    | '/business/analytics'
    | '/business/cart'
    | '/business/catalog'
    | '/business/checkout'
    | '/business/dashboard'
    | '/business/invoices'
    | '/business/payments'
    | '/business/profile'
    | '/business/quotes'
    | '/business/recurring'
    | '/business/register'
    | '/business/settings'
    | '/business/support'
    | '/driver/ai'
    | '/driver/dashboard'
    | '/driver/history'
    | '/driver/navigation'
    | '/driver/notifications'
    | '/driver/profile'
    | '/driver/support'
    | '/farmer/ai'
    | '/farmer/dashboard'
    | '/farmer/earnings'
    | '/farmer/inventory'
    | '/farmer/notifications'
    | '/farmer/payments'
    | '/farmer/pickups'
    | '/farmer/profile'
    | '/farmer/register'
    | '/farmer/settings'
    | '/farmer/support'
    | '/godown/ai'
    | '/godown/alerts'
    | '/godown/allocation'
    | '/godown/batches'
    | '/godown/cold-storage'
    | '/godown/dashboard'
    | '/godown/employees'
    | '/godown/expiry'
    | '/godown/inbound'
    | '/godown/inventory'
    | '/godown/locations'
    | '/godown/outbound'
    | '/godown/reports'
    | '/godown/settings'
    | '/godown/tasks'
    | '/office/compliance'
    | '/office/dashboard'
    | '/office/reconciliation'
    | '/office/reports'
    | '/products/$productId'
    | '/recruitment/ai'
    | '/recruitment/analytics'
    | '/recruitment/dashboard'
    | '/recruitment/directory'
    | '/recruitment/onboarding'
    | '/recruitment/settings'
    | '/transport/ai'
    | '/transport/assignments'
    | '/transport/bulk-logistics'
    | '/transport/dashboard'
    | '/transport/history'
    | '/transport/home-delivery'
    | '/transport/maintenance'
    | '/transport/more'
    | '/transport/queue'
    | '/transport/shifts'
    | '/transport/tracking'
    | '/business/'
    | '/categories/'
    | '/checkout/'
    | '/driver/'
    | '/farmer/'
    | '/godown/'
    | '/products/'
    | '/recruitment/'
    | '/transport/'
    | '/business/orders/$orderId'
    | '/business/products/$productId'
    | '/driver/deliveries/$orderId'
    | '/driver/deliveries/pickup-verification'
    | '/driver/deliveries/proof-of-delivery'
    | '/driver/deliveries/report-problem'
    | '/driver/deliveries/success'
    | '/farmer/orders/$orderId'
    | '/farmer/products/add'
    | '/godown/products/$productId'
    | '/godown/products/history'
    | '/godown/products/new'
    | '/recruitment/applications/details'
    | '/business/orders/'
    | '/driver/deliveries/'
    | '/driver/vehicle/'
    | '/farmer/orders/'
    | '/farmer/products/'
    | '/godown/products/'
    | '/recruitment/accounts/'
    | '/recruitment/applications/'
    | '/recruitment/verification/'
    | '/transport/alerts/'
    | '/transport/drivers/'
    | '/transport/employees/'
    | '/transport/reports/'
    | '/transport/routes/'
    | '/transport/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  PortalSelectRoute: typeof PortalSelectRoute
  BusinessAiRoute: typeof BusinessAiRoute
  BusinessAnalyticsRoute: typeof BusinessAnalyticsRoute
  BusinessCartRoute: typeof BusinessCartRoute
  BusinessCatalogRoute: typeof BusinessCatalogRoute
  BusinessCheckoutRoute: typeof BusinessCheckoutRoute
  BusinessDashboardRoute: typeof BusinessDashboardRoute
  BusinessInvoicesRoute: typeof BusinessInvoicesRoute
  BusinessPaymentsRoute: typeof BusinessPaymentsRoute
  BusinessProfileRoute: typeof BusinessProfileRoute
  BusinessQuotesRoute: typeof BusinessQuotesRoute
  BusinessRecurringRoute: typeof BusinessRecurringRoute
  BusinessRegisterRoute: typeof BusinessRegisterRoute
  BusinessSettingsRoute: typeof BusinessSettingsRoute
  BusinessSupportRoute: typeof BusinessSupportRoute
  DriverAiRoute: typeof DriverAiRoute
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverHistoryRoute: typeof DriverHistoryRoute
  DriverNavigationRoute: typeof DriverNavigationRoute
  DriverNotificationsRoute: typeof DriverNotificationsRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverSupportRoute: typeof DriverSupportRoute
  FarmerAiRoute: typeof FarmerAiRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  FarmerEarningsRoute: typeof FarmerEarningsRoute
  FarmerInventoryRoute: typeof FarmerInventoryRoute
  FarmerNotificationsRoute: typeof FarmerNotificationsRoute
  FarmerPaymentsRoute: typeof FarmerPaymentsRoute
  FarmerPickupsRoute: typeof FarmerPickupsRoute
  FarmerProfileRoute: typeof FarmerProfileRoute
  FarmerRegisterRoute: typeof FarmerRegisterRoute
  FarmerSettingsRoute: typeof FarmerSettingsRoute
  FarmerSupportRoute: typeof FarmerSupportRoute
  GodownAiRoute: typeof GodownAiRoute
  GodownAlertsRoute: typeof GodownAlertsRoute
  GodownAllocationRoute: typeof GodownAllocationRoute
  GodownBatchesRoute: typeof GodownBatchesRoute
  GodownColdStorageRoute: typeof GodownColdStorageRoute
  GodownDashboardRoute: typeof GodownDashboardRoute
  GodownEmployeesRoute: typeof GodownEmployeesRoute
  GodownExpiryRoute: typeof GodownExpiryRoute
  GodownInboundRoute: typeof GodownInboundRoute
  GodownInventoryRoute: typeof GodownInventoryRoute
  GodownLocationsRoute: typeof GodownLocationsRoute
  GodownOutboundRoute: typeof GodownOutboundRoute
  GodownReportsRoute: typeof GodownReportsRoute
  GodownSettingsRoute: typeof GodownSettingsRoute
  GodownTasksRoute: typeof GodownTasksRoute
  OfficeComplianceRoute: typeof OfficeComplianceRoute
  OfficeDashboardRoute: typeof OfficeDashboardRoute
  OfficeReconciliationRoute: typeof OfficeReconciliationRoute
  OfficeReportsRoute: typeof OfficeReportsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  RecruitmentAiRoute: typeof RecruitmentAiRoute
  RecruitmentAnalyticsRoute: typeof RecruitmentAnalyticsRoute
  RecruitmentDashboardRoute: typeof RecruitmentDashboardRoute
  RecruitmentDirectoryRoute: typeof RecruitmentDirectoryRoute
  RecruitmentOnboardingRoute: typeof RecruitmentOnboardingRoute
  RecruitmentSettingsRoute: typeof RecruitmentSettingsRoute
  TransportAiRoute: typeof TransportAiRoute
  TransportAssignmentsRoute: typeof TransportAssignmentsRoute
  TransportBulkLogisticsRoute: typeof TransportBulkLogisticsRoute
  TransportDashboardRoute: typeof TransportDashboardRoute
  TransportHistoryRoute: typeof TransportHistoryRoute
  TransportHomeDeliveryRoute: typeof TransportHomeDeliveryRoute
  TransportMaintenanceRoute: typeof TransportMaintenanceRoute
  TransportMoreRoute: typeof TransportMoreRoute
  TransportQueueRoute: typeof TransportQueueRoute
  TransportShiftsRoute: typeof TransportShiftsRoute
  TransportTrackingRoute: typeof TransportTrackingRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  GodownIndexRoute: typeof GodownIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RecruitmentIndexRoute: typeof RecruitmentIndexRoute
  TransportIndexRoute: typeof TransportIndexRoute
  BusinessOrdersOrderIdRoute: typeof BusinessOrdersOrderIdRoute
  BusinessProductsProductIdRoute: typeof BusinessProductsProductIdRoute
  DriverDeliveriesOrderIdRoute: typeof DriverDeliveriesOrderIdRoute
  DriverDeliveriesPickupVerificationRoute: typeof DriverDeliveriesPickupVerificationRoute
  DriverDeliveriesProofOfDeliveryRoute: typeof DriverDeliveriesProofOfDeliveryRoute
  DriverDeliveriesReportProblemRoute: typeof DriverDeliveriesReportProblemRoute
  DriverDeliveriesSuccessRoute: typeof DriverDeliveriesSuccessRoute
  FarmerOrdersOrderIdRoute: typeof FarmerOrdersOrderIdRoute
  FarmerProductsAddRoute: typeof FarmerProductsAddRoute
  GodownProductsProductIdRoute: typeof GodownProductsProductIdRoute
  GodownProductsHistoryRoute: typeof GodownProductsHistoryRoute
  GodownProductsNewRoute: typeof GodownProductsNewRoute
  RecruitmentApplicationsDetailsRoute: typeof RecruitmentApplicationsDetailsRoute
  BusinessOrdersIndexRoute: typeof BusinessOrdersIndexRoute
  DriverDeliveriesIndexRoute: typeof DriverDeliveriesIndexRoute
  DriverVehicleIndexRoute: typeof DriverVehicleIndexRoute
  FarmerOrdersIndexRoute: typeof FarmerOrdersIndexRoute
  FarmerProductsIndexRoute: typeof FarmerProductsIndexRoute
  GodownProductsIndexRoute: typeof GodownProductsIndexRoute
  RecruitmentAccountsIndexRoute: typeof RecruitmentAccountsIndexRoute
  RecruitmentApplicationsIndexRoute: typeof RecruitmentApplicationsIndexRoute
  RecruitmentVerificationIndexRoute: typeof RecruitmentVerificationIndexRoute
  TransportAlertsIndexRoute: typeof TransportAlertsIndexRoute
  TransportDriversIndexRoute: typeof TransportDriversIndexRoute
  TransportEmployeesIndexRoute: typeof TransportEmployeesIndexRoute
  TransportReportsIndexRoute: typeof TransportReportsIndexRoute
  TransportRoutesIndexRoute: typeof TransportRoutesIndexRoute
  TransportVehiclesIndexRoute: typeof TransportVehiclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-select': {
      id: '/portal-select'
      path: '/portal-select'
      fullPath: '/portal-select'
      preLoaderRoute: typeof PortalSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/ai': {
      id: '/business/ai'
      path: '/business/ai'
      fullPath: '/business/ai'
      preLoaderRoute: typeof BusinessAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/analytics': {
      id: '/business/analytics'
      path: '/business/analytics'
      fullPath: '/business/analytics'
      preLoaderRoute: typeof BusinessAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/cart': {
      id: '/business/cart'
      path: '/business/cart'
      fullPath: '/business/cart'
      preLoaderRoute: typeof BusinessCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/catalog': {
      id: '/business/catalog'
      path: '/business/catalog'
      fullPath: '/business/catalog'
      preLoaderRoute: typeof BusinessCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/checkout': {
      id: '/business/checkout'
      path: '/business/checkout'
      fullPath: '/business/checkout'
      preLoaderRoute: typeof BusinessCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/dashboard': {
      id: '/business/dashboard'
      path: '/business/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof BusinessDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/invoices': {
      id: '/business/invoices'
      path: '/business/invoices'
      fullPath: '/business/invoices'
      preLoaderRoute: typeof BusinessInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/payments': {
      id: '/business/payments'
      path: '/business/payments'
      fullPath: '/business/payments'
      preLoaderRoute: typeof BusinessPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/profile': {
      id: '/business/profile'
      path: '/business/profile'
      fullPath: '/business/profile'
      preLoaderRoute: typeof BusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/quotes': {
      id: '/business/quotes'
      path: '/business/quotes'
      fullPath: '/business/quotes'
      preLoaderRoute: typeof BusinessQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/recurring': {
      id: '/business/recurring'
      path: '/business/recurring'
      fullPath: '/business/recurring'
      preLoaderRoute: typeof BusinessRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/register': {
      id: '/business/register'
      path: '/business/register'
      fullPath: '/business/register'
      preLoaderRoute: typeof BusinessRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/settings': {
      id: '/business/settings'
      path: '/business/settings'
      fullPath: '/business/settings'
      preLoaderRoute: typeof BusinessSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/support': {
      id: '/business/support'
      path: '/business/support'
      fullPath: '/business/support'
      preLoaderRoute: typeof BusinessSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/ai': {
      id: '/driver/ai'
      path: '/driver/ai'
      fullPath: '/driver/ai'
      preLoaderRoute: typeof DriverAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/driver/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/history': {
      id: '/driver/history'
      path: '/driver/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/navigation': {
      id: '/driver/navigation'
      path: '/driver/navigation'
      fullPath: '/driver/navigation'
      preLoaderRoute: typeof DriverNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/notifications': {
      id: '/driver/notifications'
      path: '/driver/notifications'
      fullPath: '/driver/notifications'
      preLoaderRoute: typeof DriverNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/driver/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/support': {
      id: '/driver/support'
      path: '/driver/support'
      fullPath: '/driver/support'
      preLoaderRoute: typeof DriverSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/farmer'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/ai': {
      id: '/farmer/ai'
      path: '/farmer/ai'
      fullPath: '/farmer/ai'
      preLoaderRoute: typeof FarmerAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/dashboard': {
      id: '/farmer/dashboard'
      path: '/farmer/dashboard'
      fullPath: '/farmer/dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/earnings': {
      id: '/farmer/earnings'
      path: '/farmer/earnings'
      fullPath: '/farmer/earnings'
      preLoaderRoute: typeof FarmerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/inventory': {
      id: '/farmer/inventory'
      path: '/farmer/inventory'
      fullPath: '/farmer/inventory'
      preLoaderRoute: typeof FarmerInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/notifications': {
      id: '/farmer/notifications'
      path: '/farmer/notifications'
      fullPath: '/farmer/notifications'
      preLoaderRoute: typeof FarmerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/payments': {
      id: '/farmer/payments'
      path: '/farmer/payments'
      fullPath: '/farmer/payments'
      preLoaderRoute: typeof FarmerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/pickups': {
      id: '/farmer/pickups'
      path: '/farmer/pickups'
      fullPath: '/farmer/pickups'
      preLoaderRoute: typeof FarmerPickupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/profile': {
      id: '/farmer/profile'
      path: '/farmer/profile'
      fullPath: '/farmer/profile'
      preLoaderRoute: typeof FarmerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/register': {
      id: '/farmer/register'
      path: '/farmer/register'
      fullPath: '/farmer/register'
      preLoaderRoute: typeof FarmerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/settings': {
      id: '/farmer/settings'
      path: '/farmer/settings'
      fullPath: '/farmer/settings'
      preLoaderRoute: typeof FarmerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/support': {
      id: '/farmer/support'
      path: '/farmer/support'
      fullPath: '/farmer/support'
      preLoaderRoute: typeof FarmerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/': {
      id: '/godown/'
      path: '/godown'
      fullPath: '/godown/'
      preLoaderRoute: typeof GodownIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/ai': {
      id: '/godown/ai'
      path: '/godown/ai'
      fullPath: '/godown/ai'
      preLoaderRoute: typeof GodownAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/alerts': {
      id: '/godown/alerts'
      path: '/godown/alerts'
      fullPath: '/godown/alerts'
      preLoaderRoute: typeof GodownAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/allocation': {
      id: '/godown/allocation'
      path: '/godown/allocation'
      fullPath: '/godown/allocation'
      preLoaderRoute: typeof GodownAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/batches': {
      id: '/godown/batches'
      path: '/godown/batches'
      fullPath: '/godown/batches'
      preLoaderRoute: typeof GodownBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/cold-storage': {
      id: '/godown/cold-storage'
      path: '/godown/cold-storage'
      fullPath: '/godown/cold-storage'
      preLoaderRoute: typeof GodownColdStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/dashboard': {
      id: '/godown/dashboard'
      path: '/godown/dashboard'
      fullPath: '/godown/dashboard'
      preLoaderRoute: typeof GodownDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/employees': {
      id: '/godown/employees'
      path: '/godown/employees'
      fullPath: '/godown/employees'
      preLoaderRoute: typeof GodownEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/expiry': {
      id: '/godown/expiry'
      path: '/godown/expiry'
      fullPath: '/godown/expiry'
      preLoaderRoute: typeof GodownExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/inbound': {
      id: '/godown/inbound'
      path: '/godown/inbound'
      fullPath: '/godown/inbound'
      preLoaderRoute: typeof GodownInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/inventory': {
      id: '/godown/inventory'
      path: '/godown/inventory'
      fullPath: '/godown/inventory'
      preLoaderRoute: typeof GodownInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/locations': {
      id: '/godown/locations'
      path: '/godown/locations'
      fullPath: '/godown/locations'
      preLoaderRoute: typeof GodownLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/outbound': {
      id: '/godown/outbound'
      path: '/godown/outbound'
      fullPath: '/godown/outbound'
      preLoaderRoute: typeof GodownOutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/reports': {
      id: '/godown/reports'
      path: '/godown/reports'
      fullPath: '/godown/reports'
      preLoaderRoute: typeof GodownReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/settings': {
      id: '/godown/settings'
      path: '/godown/settings'
      fullPath: '/godown/settings'
      preLoaderRoute: typeof GodownSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/tasks': {
      id: '/godown/tasks'
      path: '/godown/tasks'
      fullPath: '/godown/tasks'
      preLoaderRoute: typeof GodownTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/compliance': {
      id: '/office/compliance'
      path: '/office/compliance'
      fullPath: '/office/compliance'
      preLoaderRoute: typeof OfficeComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/dashboard': {
      id: '/office/dashboard'
      path: '/office/dashboard'
      fullPath: '/office/dashboard'
      preLoaderRoute: typeof OfficeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/reconciliation': {
      id: '/office/reconciliation'
      path: '/office/reconciliation'
      fullPath: '/office/reconciliation'
      preLoaderRoute: typeof OfficeReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/reports': {
      id: '/office/reports'
      path: '/office/reports'
      fullPath: '/office/reports'
      preLoaderRoute: typeof OfficeReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/': {
      id: '/recruitment/'
      path: '/recruitment'
      fullPath: '/recruitment/'
      preLoaderRoute: typeof RecruitmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/ai': {
      id: '/recruitment/ai'
      path: '/recruitment/ai'
      fullPath: '/recruitment/ai'
      preLoaderRoute: typeof RecruitmentAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/analytics': {
      id: '/recruitment/analytics'
      path: '/recruitment/analytics'
      fullPath: '/recruitment/analytics'
      preLoaderRoute: typeof RecruitmentAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/dashboard': {
      id: '/recruitment/dashboard'
      path: '/recruitment/dashboard'
      fullPath: '/recruitment/dashboard'
      preLoaderRoute: typeof RecruitmentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/directory': {
      id: '/recruitment/directory'
      path: '/recruitment/directory'
      fullPath: '/recruitment/directory'
      preLoaderRoute: typeof RecruitmentDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/onboarding': {
      id: '/recruitment/onboarding'
      path: '/recruitment/onboarding'
      fullPath: '/recruitment/onboarding'
      preLoaderRoute: typeof RecruitmentOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/settings': {
      id: '/recruitment/settings'
      path: '/recruitment/settings'
      fullPath: '/recruitment/settings'
      preLoaderRoute: typeof RecruitmentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/': {
      id: '/transport/'
      path: '/transport'
      fullPath: '/transport/'
      preLoaderRoute: typeof TransportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/ai': {
      id: '/transport/ai'
      path: '/transport/ai'
      fullPath: '/transport/ai'
      preLoaderRoute: typeof TransportAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/assignments': {
      id: '/transport/assignments'
      path: '/transport/assignments'
      fullPath: '/transport/assignments'
      preLoaderRoute: typeof TransportAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/bulk-logistics': {
      id: '/transport/bulk-logistics'
      path: '/transport/bulk-logistics'
      fullPath: '/transport/bulk-logistics'
      preLoaderRoute: typeof TransportBulkLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/dashboard': {
      id: '/transport/dashboard'
      path: '/transport/dashboard'
      fullPath: '/transport/dashboard'
      preLoaderRoute: typeof TransportDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/history': {
      id: '/transport/history'
      path: '/transport/history'
      fullPath: '/transport/history'
      preLoaderRoute: typeof TransportHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/home-delivery': {
      id: '/transport/home-delivery'
      path: '/transport/home-delivery'
      fullPath: '/transport/home-delivery'
      preLoaderRoute: typeof TransportHomeDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/maintenance': {
      id: '/transport/maintenance'
      path: '/transport/maintenance'
      fullPath: '/transport/maintenance'
      preLoaderRoute: typeof TransportMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/more': {
      id: '/transport/more'
      path: '/transport/more'
      fullPath: '/transport/more'
      preLoaderRoute: typeof TransportMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/queue': {
      id: '/transport/queue'
      path: '/transport/queue'
      fullPath: '/transport/queue'
      preLoaderRoute: typeof TransportQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/shifts': {
      id: '/transport/shifts'
      path: '/transport/shifts'
      fullPath: '/transport/shifts'
      preLoaderRoute: typeof TransportShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/tracking': {
      id: '/transport/tracking'
      path: '/transport/tracking'
      fullPath: '/transport/tracking'
      preLoaderRoute: typeof TransportTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/orders/': {
      id: '/business/orders/'
      path: '/business/orders'
      fullPath: '/business/orders/'
      preLoaderRoute: typeof BusinessOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/orders/$orderId': {
      id: '/business/orders/$orderId'
      path: '/business/orders/$orderId'
      fullPath: '/business/orders/$orderId'
      preLoaderRoute: typeof BusinessOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/products/$productId': {
      id: '/business/products/$productId'
      path: '/business/products/$productId'
      fullPath: '/business/products/$productId'
      preLoaderRoute: typeof BusinessProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/deliveries/': {
      id: '/driver/deliveries/'
      path: '/driver/deliveries'
      fullPath: '/driver/deliveries/'
      preLoaderRoute: typeof DriverDeliveriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/deliveries/$orderId': {
      id: '/driver/deliveries/$orderId'
      path: '/driver/deliveries/$orderId'
      fullPath: '/driver/deliveries/$orderId'
      preLoaderRoute: typeof DriverDeliveriesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/deliveries/pickup-verification': {
      id: '/driver/deliveries/pickup-verification'
      path: '/driver/deliveries/pickup-verification'
      fullPath: '/driver/deliveries/pickup-verification'
      preLoaderRoute: typeof DriverDeliveriesPickupVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/deliveries/proof-of-delivery': {
      id: '/driver/deliveries/proof-of-delivery'
      path: '/driver/deliveries/proof-of-delivery'
      fullPath: '/driver/deliveries/proof-of-delivery'
      preLoaderRoute: typeof DriverDeliveriesProofOfDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/deliveries/report-problem': {
      id: '/driver/deliveries/report-problem'
      path: '/driver/deliveries/report-problem'
      fullPath: '/driver/deliveries/report-problem'
      preLoaderRoute: typeof DriverDeliveriesReportProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/deliveries/success': {
      id: '/driver/deliveries/success'
      path: '/driver/deliveries/success'
      fullPath: '/driver/deliveries/success'
      preLoaderRoute: typeof DriverDeliveriesSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/vehicle/': {
      id: '/driver/vehicle/'
      path: '/driver/vehicle'
      fullPath: '/driver/vehicle/'
      preLoaderRoute: typeof DriverVehicleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/orders/': {
      id: '/farmer/orders/'
      path: '/farmer/orders'
      fullPath: '/farmer/orders/'
      preLoaderRoute: typeof FarmerOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/orders/$orderId': {
      id: '/farmer/orders/$orderId'
      path: '/farmer/orders/$orderId'
      fullPath: '/farmer/orders/$orderId'
      preLoaderRoute: typeof FarmerOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/products/': {
      id: '/farmer/products/'
      path: '/farmer/products'
      fullPath: '/farmer/products/'
      preLoaderRoute: typeof FarmerProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/products/add': {
      id: '/farmer/products/add'
      path: '/farmer/products/add'
      fullPath: '/farmer/products/add'
      preLoaderRoute: typeof FarmerProductsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/products/': {
      id: '/godown/products/'
      path: '/godown/products'
      fullPath: '/godown/products/'
      preLoaderRoute: typeof GodownProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/products/$productId': {
      id: '/godown/products/$productId'
      path: '/godown/products/$productId'
      fullPath: '/godown/products/$productId'
      preLoaderRoute: typeof GodownProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/products/history': {
      id: '/godown/products/history'
      path: '/godown/products/history'
      fullPath: '/godown/products/history'
      preLoaderRoute: typeof GodownProductsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godown/products/new': {
      id: '/godown/products/new'
      path: '/godown/products/new'
      fullPath: '/godown/products/new'
      preLoaderRoute: typeof GodownProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/accounts/': {
      id: '/recruitment/accounts/'
      path: '/recruitment/accounts'
      fullPath: '/recruitment/accounts/'
      preLoaderRoute: typeof RecruitmentAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/applications/': {
      id: '/recruitment/applications/'
      path: '/recruitment/applications'
      fullPath: '/recruitment/applications/'
      preLoaderRoute: typeof RecruitmentApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/applications/details': {
      id: '/recruitment/applications/details'
      path: '/recruitment/applications/details'
      fullPath: '/recruitment/applications/details'
      preLoaderRoute: typeof RecruitmentApplicationsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment/verification/': {
      id: '/recruitment/verification/'
      path: '/recruitment/verification'
      fullPath: '/recruitment/verification/'
      preLoaderRoute: typeof RecruitmentVerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/alerts/': {
      id: '/transport/alerts/'
      path: '/transport/alerts'
      fullPath: '/transport/alerts/'
      preLoaderRoute: typeof TransportAlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/drivers/': {
      id: '/transport/drivers/'
      path: '/transport/drivers'
      fullPath: '/transport/drivers/'
      preLoaderRoute: typeof TransportDriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/employees/': {
      id: '/transport/employees/'
      path: '/transport/employees'
      fullPath: '/transport/employees/'
      preLoaderRoute: typeof TransportEmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/reports/': {
      id: '/transport/reports/'
      path: '/transport/reports'
      fullPath: '/transport/reports/'
      preLoaderRoute: typeof TransportReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/routes/': {
      id: '/transport/routes/'
      path: '/transport/routes'
      fullPath: '/transport/routes/'
      preLoaderRoute: typeof TransportRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/vehicles/': {
      id: '/transport/vehicles/'
      path: '/transport/vehicles'
      fullPath: '/transport/vehicles/'
      preLoaderRoute: typeof TransportVehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  PortalSelectRoute: PortalSelectRoute,
  BusinessAiRoute: BusinessAiRoute,
  BusinessAnalyticsRoute: BusinessAnalyticsRoute,
  BusinessCartRoute: BusinessCartRoute,
  BusinessCatalogRoute: BusinessCatalogRoute,
  BusinessCheckoutRoute: BusinessCheckoutRoute,
  BusinessDashboardRoute: BusinessDashboardRoute,
  BusinessInvoicesRoute: BusinessInvoicesRoute,
  BusinessPaymentsRoute: BusinessPaymentsRoute,
  BusinessProfileRoute: BusinessProfileRoute,
  BusinessQuotesRoute: BusinessQuotesRoute,
  BusinessRecurringRoute: BusinessRecurringRoute,
  BusinessRegisterRoute: BusinessRegisterRoute,
  BusinessSettingsRoute: BusinessSettingsRoute,
  BusinessSupportRoute: BusinessSupportRoute,
  DriverAiRoute: DriverAiRoute,
  DriverDashboardRoute: DriverDashboardRoute,
  DriverHistoryRoute: DriverHistoryRoute,
  DriverNavigationRoute: DriverNavigationRoute,
  DriverNotificationsRoute: DriverNotificationsRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverSupportRoute: DriverSupportRoute,
  FarmerAiRoute: FarmerAiRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  FarmerEarningsRoute: FarmerEarningsRoute,
  FarmerInventoryRoute: FarmerInventoryRoute,
  FarmerNotificationsRoute: FarmerNotificationsRoute,
  FarmerPaymentsRoute: FarmerPaymentsRoute,
  FarmerPickupsRoute: FarmerPickupsRoute,
  FarmerProfileRoute: FarmerProfileRoute,
  FarmerRegisterRoute: FarmerRegisterRoute,
  FarmerSettingsRoute: FarmerSettingsRoute,
  FarmerSupportRoute: FarmerSupportRoute,
  GodownAiRoute: GodownAiRoute,
  GodownAlertsRoute: GodownAlertsRoute,
  GodownAllocationRoute: GodownAllocationRoute,
  GodownBatchesRoute: GodownBatchesRoute,
  GodownColdStorageRoute: GodownColdStorageRoute,
  GodownDashboardRoute: GodownDashboardRoute,
  GodownEmployeesRoute: GodownEmployeesRoute,
  GodownExpiryRoute: GodownExpiryRoute,
  GodownInboundRoute: GodownInboundRoute,
  GodownInventoryRoute: GodownInventoryRoute,
  GodownLocationsRoute: GodownLocationsRoute,
  GodownOutboundRoute: GodownOutboundRoute,
  GodownReportsRoute: GodownReportsRoute,
  GodownSettingsRoute: GodownSettingsRoute,
  GodownTasksRoute: GodownTasksRoute,
  OfficeComplianceRoute: OfficeComplianceRoute,
  OfficeDashboardRoute: OfficeDashboardRoute,
  OfficeReconciliationRoute: OfficeReconciliationRoute,
  OfficeReportsRoute: OfficeReportsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  RecruitmentAiRoute: RecruitmentAiRoute,
  RecruitmentAnalyticsRoute: RecruitmentAnalyticsRoute,
  RecruitmentDashboardRoute: RecruitmentDashboardRoute,
  RecruitmentDirectoryRoute: RecruitmentDirectoryRoute,
  RecruitmentOnboardingRoute: RecruitmentOnboardingRoute,
  RecruitmentSettingsRoute: RecruitmentSettingsRoute,
  TransportAiRoute: TransportAiRoute,
  TransportAssignmentsRoute: TransportAssignmentsRoute,
  TransportBulkLogisticsRoute: TransportBulkLogisticsRoute,
  TransportDashboardRoute: TransportDashboardRoute,
  TransportHistoryRoute: TransportHistoryRoute,
  TransportHomeDeliveryRoute: TransportHomeDeliveryRoute,
  TransportMaintenanceRoute: TransportMaintenanceRoute,
  TransportMoreRoute: TransportMoreRoute,
  TransportQueueRoute: TransportQueueRoute,
  TransportShiftsRoute: TransportShiftsRoute,
  TransportTrackingRoute: TransportTrackingRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  GodownIndexRoute: GodownIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RecruitmentIndexRoute: RecruitmentIndexRoute,
  TransportIndexRoute: TransportIndexRoute,
  BusinessOrdersOrderIdRoute: BusinessOrdersOrderIdRoute,
  BusinessProductsProductIdRoute: BusinessProductsProductIdRoute,
  DriverDeliveriesOrderIdRoute: DriverDeliveriesOrderIdRoute,
  DriverDeliveriesPickupVerificationRoute:
    DriverDeliveriesPickupVerificationRoute,
  DriverDeliveriesProofOfDeliveryRoute: DriverDeliveriesProofOfDeliveryRoute,
  DriverDeliveriesReportProblemRoute: DriverDeliveriesReportProblemRoute,
  DriverDeliveriesSuccessRoute: DriverDeliveriesSuccessRoute,
  FarmerOrdersOrderIdRoute: FarmerOrdersOrderIdRoute,
  FarmerProductsAddRoute: FarmerProductsAddRoute,
  GodownProductsProductIdRoute: GodownProductsProductIdRoute,
  GodownProductsHistoryRoute: GodownProductsHistoryRoute,
  GodownProductsNewRoute: GodownProductsNewRoute,
  RecruitmentApplicationsDetailsRoute: RecruitmentApplicationsDetailsRoute,
  BusinessOrdersIndexRoute: BusinessOrdersIndexRoute,
  DriverDeliveriesIndexRoute: DriverDeliveriesIndexRoute,
  DriverVehicleIndexRoute: DriverVehicleIndexRoute,
  FarmerOrdersIndexRoute: FarmerOrdersIndexRoute,
  FarmerProductsIndexRoute: FarmerProductsIndexRoute,
  GodownProductsIndexRoute: GodownProductsIndexRoute,
  RecruitmentAccountsIndexRoute: RecruitmentAccountsIndexRoute,
  RecruitmentApplicationsIndexRoute: RecruitmentApplicationsIndexRoute,
  RecruitmentVerificationIndexRoute: RecruitmentVerificationIndexRoute,
  TransportAlertsIndexRoute: TransportAlertsIndexRoute,
  TransportDriversIndexRoute: TransportDriversIndexRoute,
  TransportEmployeesIndexRoute: TransportEmployeesIndexRoute,
  TransportReportsIndexRoute: TransportReportsIndexRoute,
  TransportRoutesIndexRoute: TransportRoutesIndexRoute,
  TransportVehiclesIndexRoute: TransportVehiclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
